test-results-reporter/testbeats

- package-lock.json
- package.json
- src/commands/publish.js
- src/extensions/index.js
- src/extensions/report-portal-analysis.js
- src/helpers/helper.js
- src/helpers/report-portal.js
- src/index.d.ts
- src/index.js
- src/targets/slack.js
- src/targets/teams.js
- test/data/configs/custom-target.json
- test/data/configs/failure-all-reports-failures.json
- test/data/configs/failure-all-reports-no-failures.json
- test/data/configs/report-portal-analysis.json
- test/publish.spec.js
> 4 support extensions for targets teams slack

- package-lock.json
- package.json
- src/extensions/index.js
- src/extensions/mentions.js
- src/extensions/report-portal-analysis.js
- src/index.d.ts
- src/targets/teams.js
- test/ext.mentions.spec.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
> feat: support mentions

- .github/workflows/build.yml
- package-lock.json
- package.json
- src/targets/delay.js
- src/targets/index.js
- test/targets.delay.spec.js
> feat: added delay target

- src/extensions/index.js
- src/extensions/quick-charts-test-summary.js
- src/targets/slack.js
- src/targets/teams.js
- test/ext.quick-charts-test-summary.spec.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
> 18 extension quick charts

- src/extensions/hyperlinks.js
- src/helpers/constants.js
- test/ext.hyperlink.spec.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
closes #7 
Change Summary:
- Added `Constants.js` for all constants.
- Logic for conditionally attaching the hyperlinks based on test result status.
- Slack and teams mock changes.
- Addition/update of test cases
> Conditional Hyperlinks support on slack and teams

- package-lock.json
- package.json
- src/index.d.ts
- src/targets/teams.js
- test/mocks/teams.mock.js
- test/targets.teams.spec.js
> 31 teams support wrap text and full width

- package-lock.json
- package.json
- src/extensions/hyperlinks.js
- src/extensions/index.js
- src/extensions/mentions.js
- src/extensions/report-portal-analysis.js
- src/extensions/report-portal-history.js
- src/helpers/constants.js
- src/helpers/slack.js
- src/helpers/teams.js
- src/index.d.ts
- src/targets/index.js
- src/targets/slack.js
- src/targets/teams.js
- test/ext.hyperlink.spec.js
- test/ext.report-portal-analysis.spec.js
- test/ext.report-portal-history.spec.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
> 40 configurable titles and dividers for all extensions

- src/extensions/hyperlinks.js
- src/extensions/index.js
- src/helpers/helper.js
- src/index.d.ts
- src/targets/index.js
- test/condition.spec.js
> support advanced conditions

- package-lock.json
- package.json
- src/extensions/index.js
- src/extensions/percy-analysis.js
- src/extensions/report-portal-analysis.js
- src/helpers/percy.js
- src/index.d.ts
- test/ext.percy-analysis.spec.js
- test/mocks/chat.mock.js
- test/mocks/percy.mock.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
> 61 extension percy enhancements

- src/index.d.ts
- src/targets/chat.js
- src/targets/slack.js
- src/targets/teams.js
- test/mocks/chat.mock.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
- test/targets.chat.spec.js
- test/targets.slack.spec.js
- test/targets.teams.spec.js
> feat: title links

- package-lock.json
- package.json
- src/extensions/hyperlinks.js
- src/index.d.ts
- src/index.js
- test/ext.hyperlink.spec.js
> feat: functional hyperlinks and defineConfig

- .github/workflows/assets-test.yml
- .github/workflows/assets.yml
- .github/workflows/publish.yml
- package-lock.json
- package.json
> feat: publish executable file on GitHub releases

- src/extensions/report-portal-analysis.js
- src/extensions/report-portal-history.js
- test/mocks/chat.mock.js
- test/mocks/rp.mock.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
> feat: link to report portal history and analysis

- package-lock.json
- package.json
- src/helpers/performance.js
- src/targets/chat.js
- src/targets/slack.js
- src/targets/teams.js
- test/helpers/interactions.js
- test/mocks/chat.mock.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
> feat: duration from colon-notation to pretty

- package-lock.json
- package.json
- src/targets/slack.js
- src/targets/teams.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
- test/targets.slack.spec.js
- test/targets.teams.spec.js
> feat:support performance test results in slack

- package-lock.json
- package.json
- src/commands/publish.js
- src/index.d.ts
- test/results.custom.spec.js
> feat: support custom result

- src/extensions/percy-analysis.js
This pull request addresses the fix for including Percy's failed build state in the getLastFinishedBuild function. The function has been updated to check for both "finished" and "failed" states and throws an error if the build is in any other state. The code has been further enhanced with error handling and added defensive checks for null handling in the function getAnalysisSummary. Overall, this PR aims to provide a more robust and reliable implementation for handling percy's build states.
Tested with possible Percy's build states (as far as I see) below and please review the changes.
> Fix #113 - Include Percy's failed build state, and add defensive checks for null handling

- src/extensions/quick-chart-test-summary.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
> fix: reduce font size to support 100% in quick chart

- src/beats/index.js
- src/index.d.ts
- src/targets/chat.js
- src/targets/slack.js
- src/targets/teams.js
> feat: added max_suites to restrict message length

- package-lock.json
- package.json
- src/extensions/ci-info.js
- src/extensions/index.js
- src/helpers/metadata.helper.js
- src/index.d.ts
- test/ext-ci-info.spec.js
- test/mocks/slack.mock.js
- test/mocks/teams.mock.js
> feat: added ceat info

- src/beats/index.js
- src/extensions/ai-failure-summary.js
- src/extensions/index.js
- src/helpers/constants.js
- src/index.d.ts
- test/beats.spec.js
- test/mocks/beats.mock.js
- test/mocks/teams.mock.js
> feat: ai failure summary

- src/beats/index.js
- src/cli.js
- src/commands/publish.js
- src/extensions/index.js
- src/extensions/report-portal-history.js
- src/helpers/colors.js
- src/utils/logger.js
**Summary:**
- Add logger setup
- Convert console.log to use logger
- Added few logs indicating process initiation and completion
> Add logger setup

- src/extensions/smart-analysis.extension.js
- test/mocks/teams.mock.js
This PR contains changes for Always Failing(AF) and Flaky Test(FL) emojis.
> fix: updated AF and FL with new emojis

- src/targets/slack.js
- test/mocks/slack.mock.js
I didn't manually test this but the change is trivial. Automated tests also failed locally but it didn't seem related to this change: `StatusCodeError: 404 - Interaction Not Found`
Fixes #179
> Include fallback text for Slack notifications (#179)

- package-lock.json
- package.json
**Summary**
- version bump v2.1.7
> chore: version bump v2.1.7
